function Hd = Eqq
%EQQ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 28-Apr-2026 09:40:19

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 257;  % Sampling Frequency

Fpass = 10;              % Passband Frequency
Fstop = 25;              % Stopband Frequency
Dpass = 0.028774368332;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
