function Hd = Filtro_blackman
%FILTRO_BLACKMAN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 27-Apr-2026 18:05:36

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 257;  % Sampling Frequency

N    = 10;       % Order
Fc   = 25;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = blackman(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
